export const AUTH_METHODS = {
  PASSWORD: 'PASSWORD',
  EMAIL_OTP: 'EMAIL_OTP'
};

export const LOGIN_STEPS = {
  LOGIN: 'login',
  LOGIN_PASSWORD: 'login-password',
  SETUP_TOTP: 'setup-totp',
  CONFIRM_TOTP: 'confirm-totp',
  CONFIRM_EMAIL_OTP: 'confirm-email-otp'
};

export const REGISTER_STEPS = {
  REGISTER: 'register',
  CONFIRM: 'confirm'
};

export const COGNITO_SIGN_IN_STEPS = {
  CONTINUE_TOTP_SETUP: 'CONTINUE_SIGN_IN_WITH_TOTP_SETUP',
  CONFIRM_TOTP_CODE: 'CONFIRM_SIGN_IN_WITH_TOTP_CODE',
  CONFIRM_OTP_CODE: 'CONFIRM_SIGN_IN_WITH_OTP_CODE',
  CONFIRM_EMAIL_CODE: 'CONFIRM_SIGN_IN_WITH_EMAIL_CODE',
  CONTINUE_FIRST_FACTOR_SELECTION: 'CONTINUE_SIGN_IN_WITH_FIRST_FACTOR_SELECTION',
  CONTINUE_MFA_SELECTION: 'CONTINUE_SIGN_IN_WITH_MFA_SELECTION'
};

export const COGNITO_FACTORS = {
  PASSWORD_SRP: 'PASSWORD_SRP',
  PASSWORD: 'PASSWORD',
  EMAIL_OTP: 'EMAIL_OTP',
  TOTP: 'TOTP'
};
